theme: jekyll-theme-minimal
title: Rcoven's homepage
description: Site for upcoming class projects and assignments
links:
  name: Cartoons
  url: https://github.com/rcoven24/rcoven24.github.io/cartoons.html
  name: New User
  url: https://github.com/rcoven24/rcoven24.github.io/newuser.html
